name: Demo Action with Email Step

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 22f3000780@ds.study.iitm.ac.in
        run: echo "Hello, world!"
